name: Monthly Release

on:
  schedule:
    - cron: "0 0 1 * *" # Schedule to run first of every month at midnight (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Makefile
        run: |
          # Replace this with the command to run your Makefile script
          make all
          zip -r wordlists.zip . -x ".*"

      - name: Set release date
        id: set_release_date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload wordlists to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wordlists.zip
          asset_name: wordlists.zip
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true
          body: "Wordlists archived on ${{ env.RELEASE_DATE }}."
