name: Weekly Release

on:
  schedule:
    - cron: "0 0 * * 0" # Schedule to run every Sunday at midnight (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Makefile
        run: |
          # Replace this with the command to run your Makefile script
          make

      - name: Set release date
        id: set_release_date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to create releases
        with:
          tag_name: ${{ env.RELEASE_DATE }} # Use the current date as the tag
          release_name: "Release ${{ env.RELEASE_DATE }}" # Use the current date in the release name
          draft: false
          prerelease: false

